import React from "react";
import Head from "next/head";
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import Provider from "@/utils/Provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


function RootLayout({ children }) {
    return (
        <html>
            <Head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
                <html lang='en' />
            </Head>
            <body className={inter.className}>
                <Provider>
                    {children}
                </Provider>
            </body>
        </html>
    );
}

export default RootLayout;