import Image from 'next/image'
import { dehydrate, HydrationBoundary, QueryClient } from '@tanstack/react-query'
import { getWeather } from '@/api/actions';
import QueryExample from '@/components/QueryExample';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Home() {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery({
    queryKey: ["weathers"],
    queryFn: getWeather,
  })



  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <HydrationBoundary state={dehydrate(queryClient)}>
        <QueryExample />
      </HydrationBoundary >
    </main>
  )
}